## Numpy Array Opreations

In [19]:
import numpy as np;


In [20]:
arr=([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Steps",arr[1:9:2])
print("Negetive Indexing",arr[-7])



Basic Slicing [3, 4, 5, 6, 7]
With Steps [2, 4, 6, 8]
Negetive Indexing 4


## Sorting

In [21]:
arr=([6,8,2,4,2,97,5,15,6,7,7,5,23,])
print("sorted arrays is ",np.sort(arr))



array_2d=([1,2,6],[5,8,9,],[3,5,7])
print("The row wise sorting of array :",np.sort(array_2d, axis=1))

sorted arrays is  [ 2  2  4  5  5  6  6  7  7  8 15 23 97]
The row wise sorting of array : [[1 2 6]
 [5 8 9]
 [3 5 7]]


## Filtering the arrays


In [22]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
numbers=numbers[numbers %2 == 0]
print("Even no are :",numbers)


Even no are : [ 2  4  6  8 10]


## Filter with Mask

In [23]:
mask= numbers>5
print("Numbers which are greater than 5 :",numbers[mask])

Numbers which are greater than 5 : [ 6  8 10]


## Fancy Indexing VS np.where

In [24]:
indecies=[0,2,4]
print(numbers[indecies])

where_result=np.where(numbers>5)
print(where_result)
print("NP Where", numbers[where_result])

[ 2  6 10]
(array([2, 3, 4], dtype=int64),)
NP Where [ 6  8 10]


In [25]:
condation_arr=np.where(numbers > 5,"true" ,"false")
print(condation_arr)

['false' 'false' 'true' 'true' 'true']


In [26]:
origina_arr=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])  

with_newRow=np.vstack((origina_arr,new_row))
print(with_newRow)


ori_colum=np.array([[7],[8]])
new_coloum=np.hstack((origina_arr,ori_colum))
print("With new coloun",new_coloum)


[[1 2]
 [3 4]
 [5 6]]
With new coloun [[1 2 7]
 [3 4 8]]
