## Day 1 of learning numpy

In [1]:
import numpy as np;

In [6]:
ones=np.ones((2,6))
print("Ones Array",ones)

Ones Array [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
random=np.random.random((2,2))
print("Random Array",random)


Random Array [[0.63084661 0.90644723]
 [0.64869074 0.21719916]]


## Vectot Matrix and Tensor

In [21]:
arr=np.array([1,2,3,4])
print("The value of arr are :",arr)# Array is Vector


matrix=np.array([[1,2,3,4],[5,6,7,9]])
print("The value of Matrix are :",matrix)# This is Tensor


tensor=np.array([[[1,2,3,5],[5,6,9,4],
                  [2,3,6,9],[9,6,8,5]]])# Tensor has multidiminsional
print("The value of Tensor array are:",tensor)


The value of arr are : [1 2 3 4]
The value of Matrix are : [[1 2 3 4]
 [5 6 7 9]]
The value of Tensor array are: [[[1 2 3 5]
  [5 6 9 4]
  [2 3 6 9]
  [9 6 8 5]]]


## Arryay Properties

In [24]:
arr=np.array([[23,56,96,85],
             [85,96,95,82]])
print("Shape",arr.shape)
print("Size",arr.size)
print("Dimensio",arr.ndim)
print("Dtype",arr.dtype)


Shape (2, 4)
Size 8
Dimensio 2
Dtype int32
